# Generated by Django 5.2 on 2025-04-26 13:44

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contact_type', models.CharField(choices=[('LANDLORD', 'Landlord'), ('TENANT', 'Tenant')], default='TENANT', max_length=10)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_number', models.CharField(max_length=50, unique=True)),
                ('type', models.CharField(choices=[('APARTMENT', 'Apartment'), ('HOUSE', 'House'), ('CONDO', 'Condominium'), ('COMMERCIAL', 'Commercial'), ('OTHER', 'Other')], default='APARTMENT', max_length=15)),
                ('location', models.CharField(max_length=255)),
                ('value', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('VACANT', 'Vacant'), ('OCCUPIED', 'Occupied'), ('MAINTENANCE', 'Under Maintenance')], default='VACANT', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(limit_choices_to={'type': 'LANDLORD'}, on_delete=django.db.models.deletion.CASCADE, related_name='owned_units', to='core.contact')),
            ],
        ),
        migrations.CreateModel(
            name='Lease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('duration', models.IntegerField(help_text='Duration in months', validators=[django.core.validators.MinValueValidator(1)])),
                ('rent_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('payment_frequency', models.CharField(choices=[('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('SEMI_ANNUAL', 'Semi-Annual'), ('ANNUAL', 'Annual')], default='MONTHLY', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('landlord', models.ForeignKey(limit_choices_to={'type': 'LANDLORD'}, on_delete=django.db.models.deletion.CASCADE, related_name='leases_as_landlord', to='core.contact')),
                ('tenant', models.ForeignKey(limit_choices_to={'type': 'TENANT'}, on_delete=django.db.models.deletion.CASCADE, related_name='leases_as_tenant', to='core.contact')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leases', to='core.unit')),
            ],
        ),
    ]
