# Generated by Django 5.2 on 2025-04-26 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lease',
            name='landlord',
            field=models.ForeignKey(limit_choices_to={'contact_type': 'LANDLORD'}, on_delete=django.db.models.deletion.CASCADE, related_name='leases_as_landlord', to='core.contact'),
        ),
        migrations.AlterField(
            model_name='lease',
            name='tenant',
            field=models.ForeignKey(limit_choices_to={'contact_type': 'TENANT'}, on_delete=django.db.models.deletion.CASCADE, related_name='leases_as_tenant', to='core.contact'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='owner',
            field=models.ForeignKey(limit_choices_to={'contact_type': 'LANDLORD'}, on_delete=django.db.models.deletion.CASCADE, related_name='owned_units', to='core.contact'),
        ),
    ]
